In [3]:
import numpy as np


arr= np.array([1, 2, 3, 6, 4, 5])
arr1=np.flip(arr)
print(arr1)

[5 4 6 3 2 1]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(np.equal(arr1,arr2))

#also there is another method
'''arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
equal=np.equal_array(arr1,arr2)
if equal:
  print('arrays are equal')
else:
  print('arrays are not equal')'''

[[ True  True]
 [ True  True]]


In [4]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Find unique values and their counts
unique_values_x, counts_x = np.unique(x, return_counts=True)


most_frequent_index_x = np.argmax(counts_x)
most_frequent_value_x = unique_values_x[most_frequent_index_x]
indices_x = np.where(x == most_frequent_value_x)[0]

print("For array x:")
print("Most frequent value:", most_frequent_value_x)
print("Indices of the most frequent value(s):", indices_x)

# y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_index_y = np.argmax(counts_y)
most_frequent_value_y = unique_values_y[most_frequent_index_y]
indices_y = np.where(y == most_frequent_value_y)[0]

print("\nFor array y:")
print("Most frequent value:", most_frequent_value_y)
print("Indices of the most frequent value(s):", indices_y)


For array x:
Most frequent value: 1
Indices of the most frequent value(s): [0 5 7 8 9]

For array y:
Most frequent value: 1
Indices of the most frequent value(s): [0 1 2]


In [6]:
gfg = np.matrix('[4, 1, 9;12, 3, 1;4, 5, 6]')

#  Sum
total_sum = np.sum(gfg)

#  Sum  row-wise
row_sum = np.sum(gfg, axis=1)

#  Sum  column-wise
col_sum = np.sum(gfg, axis=0)


print("Matrix:")
print(gfg)

print("Sum of all elements:", total_sum)

print(" Sum of all elements row-wise:")
print(row_sum)

print(" Sum of all elements column-wise:")
print(col_sum)

Matrix:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements: 45
 Sum of all elements row-wise:
[[14]
 [16]
 [15]]
 Sum of all elements column-wise:
[[20  9 16]]
